
/*
===============================================================================
Analytical Queries: Business Intelligence Layer
===============================================================================
Script Purpose:
    This script answers business questions using SQL aggregation,
    joins, and window functions on the normalized 3NF schema.

Analysis Categories:
    - Revenue Analysis
    - Customer Behavior
    - Seller Performance
    - Payment Distribution
    - Delivery Performance
    - Revenue Growth (Advanced Window Functions)

Execution Notes:
    - Queries are independent and separated by clear comment headers.
    - Designed for SQL Server.
===============================================================================
*/

-- Q1: Top 10 customers by total spending

SELECT TOP 10 
    c.customer_unique_id,
    SUM(p.payment_value) AS total_spent
FROM customer c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payment p 
    ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spent DESC;

-- Q2: Total revenue per state, ordered by highest revenue
-- Total revenue per seller state, ordered by highest revenue.
--      Revenue is generated by sellers.
--      Companies want to know which regions are strong in sales.
--      It helps with logistics, expansion, and supply chain decisions.

SELECT 
    s.seller_state,
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM seller s
JOIN order_item oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_state
ORDER BY total_revenue DESC;

-- Q3: Top 5 sellers by total revenue

SELECT TOP 5
    s.seller_id,
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM seller s
JOIN order_item oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY total_revenue DESC;

-- Q3: Top 5 sellers by total revenue with order count
-- gives deeper insight:
-- Revenue performance
-- Order volume
-- Geographic strength
-- Seller efficiency
--      High revenue + low orders → expensive products
--      Low revenue + high orders → low-margin/high-volume seller

SELECT TOP 5
    s.seller_id,
    s.seller_state,
    SUM(oi.price + oi.freight_value) AS total_revenue,
    COUNT(DISTINCT oi.order_id) AS total_orders
FROM seller s
JOIN order_item oi
    ON s.seller_id = oi.seller_id
GROUP BY 
    s.seller_id,
    s.seller_state
ORDER BY total_revenue DESC;

-- Q4: Average review score per product category
-- Not applicable: Review data not available in provided dataset.

-- Q5: Monthly revenue trend (group by year-month)
-- Q5: Monthly revenue trend

SELECT 
    YEAR(o.order_purchase_timestamp) AS order_year,
    MONTH(o.order_purchase_timestamp) AS order_month,
    SUM(p.payment_value) AS total_revenue
FROM orders o
JOIN payment p
    ON o.order_id = p.order_id
GROUP BY 
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)
ORDER BY 
    order_year,
    order_month;

-- Q6: Top 5 product categories by number of orders
-- DISTINCT is required to avoid counting the same order multiple times
-- when an order contains multiple products from the same category.
SELECT TOP 5
    p.product_category_name,
    COUNT(DISTINCT oi.order_id) AS total_orders
FROM order_item oi
JOIN product p 
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY total_orders DESC;


-- Q7: Customers who placed more than 3 orders

SELECT 
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS total_orders_per_customer
FROM customer c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(DISTINCT o.order_id) > 3
ORDER BY total_orders_per_customer DESC;

-- Q8: Orders with highest freight-to-product price ratio

SELECT TOP 10
    oi.order_id,
    SUM(oi.freight_value) / NULLIF(SUM(oi.price), 0) AS freight_to_price_ratio
FROM order_item oi
GROUP BY oi.order_id
ORDER BY freight_to_price_ratio DESC;


-- Q9: Payment method distribution (percentage of each type)

SELECT
    p.payment_type,
    COUNT(*) AS total_payments,
    CAST(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER ()
        AS DECIMAL(5,2)
    ) AS percentage_of_total
FROM payment p
GROUP BY p.payment_type
ORDER BY percentage_of_total DESC;


-- Q10: Average delivery time per customer state
-- delivery performance experienced by customers in each state
-- Customer state, not seller state.

SELECT 
    c.customer_state,
    AVG(
        DATEDIFF(
            DAY,
            o.order_purchase_timestamp,
            s.order_delivered_customer_date
        )
    ) AS avg_delivery_days
FROM customer c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN shipping s
    ON o.order_id = s.order_id
WHERE s.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_days DESC;



